# 服务配置
SERVER:
  # https 域名，必填
  URL: https://qq.com
  # 签名任务并发量
  MAXJOB: 10
  # 开发模式 debug,release,test
  RUNMODE: debug
  # 读超时/s
  READTIMEOUT: 60
  # 写超时/s
  WRITETIMEOUT: 60
  # 端口
  HTTPPORT: 8888
  # 开启 https true,false
  TLS: false
  # 公钥路径
  CRT:
  # 私钥路径
  KEY:

# 日志配置
LOG:
  # 日志输出等级 fatal,error,warn,info,debug
  LEVEL: debug

# 存储配置
STORAGE:
  # 阿里云OSS服务
  ENABLEOSS: false
  BUCKETNAME:
  OSSENDPOINT:
  OSSACCESSKEYID:
  OSSACCESSKEYSECRET:

# mysql 配置（可选）
# 配置内容参考: https://gorm.io/zh_CN/docs/connecting_to_the_database.html
MYSQL:
  # 是否启用，不启用默认使用 sqlLite
  ENABLE: false
  # 连接驱动
  DSN: root:123456@tcp(127.0.0.1:3306)/db_default?charset=utf8mb4&parseTime=True&loc=Local
  # 空闲连接池中连接的最大数量
  MAXIDLE: 10
  # 打开数据库连接的最大数量
  MAXOPEN: 10
  # 连接可复用的最大时间/单位分钟
  MAXLIFETIME: 60