version: '3'
services:
  server:
    image: togettoyou/supersign-server:latest
    ports:
      - "32288:8888"
    environment:
      - SERVER.URL=https://qq.com
      - SERVER.RUNMODE=release
      - LOG.LEVEL=info