version: '3'
services:
  mysql-super-signature:
    image: docker.io/mysql:5.7
    container_name: mysql-super-signature
    ports:
      - "3336:3306"
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_DATABASE: db_super_signature
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'

  web:
    build: .
    image: super-signature:v3
    depends_on:
      - mysql-super-signature
    ports:
      - "8888:8888"
    volumes:
      - ./conf:/root/togettoyou/super-signature/conf
      - ./ios:/root/togettoyou/super-signature/ios
      - ./router/templates:/root/togettoyou/super-signature/router/templates
      - ./ios.csr:/root/togettoyou/super-signature/ios.csr
      - ./ios.key:/root/togettoyou/super-signature/ios.key
      - ./server.crt:/root/togettoyou/super-signature/server.crt
      - ./server.csr:/root/togettoyou/super-signature/server.csr
      - ./server.key:/root/togettoyou/super-signature/server.key

#  docker-compose up
#  浏览器访问 http://localhost:8888/swagger/index.html