version: '3'
services:
  server:
    image: togettoyou/supersign:latest
    ports:
      - "8888:8888"
    volumes:
      - $PWD/data:/root/togettoyou/data
    environment:
      - SERVER_URL=https://一定要修改成你的域名
      - SERVER_MAXJOB=10
      - SERVER_RUNMODE=release
      - LOG_LEVEL=info