version: '3'
services:
  server:
    image: togettoyou/supersign-server:latest
    ports:
      - "32288:8888"
    volumes:
      - $PWD/data:/root/togettoyou/data
    environment:
      - SERVER_URL=https://一定要修改成你的域名
      - SERVER_MAXJOB=10
      - SERVER_RUNMODE=release
      - LOG_LEVEL=info
      - STORAGE_ENABLEOSS=false
      - STORAGE_BUCKETNAME=阿里云OSS的BucketName
      - STORAGE_OSSENDPOINT=阿里云OSS的Endpoint
      - STORAGE_OSSACCESSKEYID=阿里云OSS的AccessKeyId
      - STORAGE_OSSACCESSKEYSECRET=阿里云OSS的AccessKeySecret
      - MYSQL_ENABLE=false
      - MYSQL_DSN=用户名:密码@tcp(IP:端口)/数据库名?charset=utf8mb4&parseTime=True&loc=Local