version: '3'
services:
  server:
    image: togettoyou/supersign-server:latest
    ports:
      - "32288:8888"
    environment:
      - SERVER.URL=https://你的域名
      - SERVER.MAXJOB=10
      - SERVER.RUNMODE=release
      - LOG.LEVEL=info
      - STORAGE.ENABLEOSS=false
      - STORAGE.BUCKETNAME=
      - STORAGE.OSSENDPOINT=
      - STORAGE.OSSACCESSKEYID=
      - STORAGE.OSSACCESSKEYSECRET=
      - MYSQL.ENABLE=false
      - MYSQL.DSN=