# 程序配置
app:
  # jwt签名秘钥，务必更改
  jwtSecret: 1ac74db6823e95cdcb3deac50856c054

# 服务配置
server:
  # 开发模式 debug,release,test
  runMode: release
  # 超时时间/单位s
  readTimeout: 0
  writeTimeout: 0
  # 端口
  httpPort: 8888
  # 启用 https
  enableHttps: false

# 日志配置
logConfig:
  # 日志记录模式 fatal,panic,dpanic,error,warn,info,debug
  level: info
  # 日志是否记录到文件 true,false
  isFile: false
  # 普通日志文件存放位置，当 isFile 为 true 时生效
  filePath: log/log.log
  # 错误日志文件存放位置，当 isFile 为 true 时生效
  errFilePath: log/err.log
  # 日志文件的最大大小（以兆字节为单位）,当 isFile 为 true 时生效
  maxSize: 100
  # 保留旧日志文件的最大天数，当 isFile 为 true 时生效
  maxAge: 7
  # 保留的最大旧日志文件数，当 isFile 为 true 时生效
  maxBackups: 10

# mysql配置
# 配置内容参考: https://gorm.io/zh_CN/docs/connecting_to_the_database.html
mysql:
  # 连接驱动
  dsn: root:123456@tcp(mysql-super-signature:3306)/db_super_signature?charset=utf8mb4&parseTime=True&loc=Local
  # 空闲连接池中连接的最大数量
  maxIdle: 10
  # 打开数据库连接的最大数量
  maxOpen: 10
  # 连接可复用的最大时间/单位分钟
  maxLifetime: 60
  # 数据库日志模式 silent,error,warn,info
  logMode: info

# 苹果IPA配置
applePath:
  # 苹果回调域名，需 https
  url: https://isign.cn.utools.club
  # 开发者账号资料保存路径
  appleAccountPath: ./ios/appleAccount/
  # 上传的IPA保存路径(保存原始ipa、mobileconfig、png文件)
  uploadPath: ./ios/upload/
  # 提供下载的IPA临时路径(提供下载的ipa和plist文件)
  temporaryDownloadPath: ./ios/temporaryDownload/

# 苹果账号配置
appleConf:
  # 添加开发者账号时是否删除账号下所有的 Certificates
  deleteAllCertificates: false