definitions:
  handler.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact: {}
  description: iOS超级签名API接口文档
  title: iOS超级签名
  version: "1.0"
paths:
  /api/v1/deleteAppleAccount:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: iss
        in: formData
        name: iss
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 删除指定苹果开发者账号
  /api/v1/deletePackage:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 删除指定IPA
  /api/v1/getAllPackage:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 获取所有IPA
  /api/v1/test:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 测试得到一个可用的苹果开发者账号
  /api/v1/uploadAppleAccount:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: p8file
        in: formData
        name: p8file
        required: true
        type: file
      - description: iss
        in: formData
        name: iss
        required: true
        type: string
      - description: kid
        in: formData
        name: kid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 上传苹果开发者账号信息
  /api/v1/uploadPackage:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: ipaFile
        in: formData
        name: ipaFile
        required: true
        type: file
      - description: summary
        in: formData
        name: summary
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 上传IPA
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
